name: Feature request
description: Suggest an idea for this project
title: "[Feature] - "
labels: ["feature"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to accomplish?
      placeholder: "As a user I want to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
